apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "advanced-gemini.fullname" . }}-config
  labels:
    {{- include "advanced-gemini.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  DEFAULT_MODEL: {{ .Values.config.defaultModel | quote }}
  NEXT_TELEMETRY_DISABLED: {{ .Values.config.nextTelemetryDisabled | quote }}
  PORT: {{ .Values.config.port | quote }}
  HOSTNAME: "0.0.0.0"

