{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "advanced-gemini.fullname" . }}
  labels:
    {{- include "advanced-gemini.labels" . | nindent 4 }}
type: Opaque
data:
  GEMINI_API_KEY: {{ .Values.secret.geminiApiKey | b64enc | quote }}
{{- end }}

