apiVersion: v1
kind: ServiceAccount
metadata:
  name: advanced-gemini
  namespace: advanced-gemini
  labels:
    app.kubernetes.io/name: advanced-gemini
    app.kubernetes.io/part-of: advanced-gemini-devops
    environment: production
automountServiceAccountToken: true

